name: flutter_datahub
description: DataHub integration for Flutter Apps.
version: 0.1.0-dev.13
homepage: https://datahubproject.net/

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  boost: ^1.8.9
  datahub: ^0.17.0-dev.23
  firebase_crashlytics: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
