name: flutter_datahub
description: DataHub integration for Flutter Apps.
version: 0.1.0-dev.18
homepage: https://datahubproject.net/

environment:
  sdk: ^3.1.0
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  boost: ^1.8.10
  datahub: ^0.17.0-dev.73
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0